### ISSUE TITLE
Crash on first boot.

### ISSUE THREAD

**Issue by persiafighter** [eliassjogreen/Unturned-auto#1]
Program crashes on first boot due to attempting to close a never shown form. I recommend to use `Application.Exit();` instead of `this.Close();` to prevent that crash from happening.
Code where error occurs:
```
public void init()
        {
            if (!File.Exists(Directory.GetCurrentDirectory() + @"\settings.txt"))
            {
                File.Create(Directory.GetCurrentDirectory() + @"\settings.txt");
                file = Directory.GetCurrentDirectory() + @"\settings.txt";
                this.Close(); //Error happens right here.
            }
```

**Comment by eliassjogreen** [comment]
Should be fixed now!

**Comment by persiafighter** [comment]
Just compiled it, seems to be fixed and working without any crashes on first startup.
However, I can't edit the settings on the first startup because 

> The process cannot access the file because it is being used by another process.

From the code, the error is again in that same area of before, but this time a different line.
Changing `File.Create(Directory.GetCurrentDirectory() + @"\settings.txt");` to `File.Create(Directory.GetCurrentDirectory() + @"\settings.txt").Close();` should do the fix for this bug.

PS: There is a side effect in my first bug report where the application doesn't exit, but starts up normally and then causes this second side effect. You could remove `Application.Exit()` from the form1, since it doesn't seem to do anything, but you would have to handle the program from then on correctly as if the file exists but is empty.
You could also place in the method "main" of program.cs, before executing the form
```
        if (!File.Exists(Directory.GetCurrentDirectory() + @"\settings.txt"))
            {
                File.Create(Directory.GetCurrentDirectory() + @"\settings.txt").Close();
                return;
            }
```
But my first suggestion of adding `.close()` to the file creation should do the trick for fixing the main side effect.

**Comment by eliassjogreen** [comment]
Might be fixed now. Still really buggy...
